version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: auth--service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  auth-service:
    build: .
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth--service
      JWT_KEY: nudlEqLbjDYY0E2qUCND2aIRu/e3huNony/Bn7bwWzo=
    ports:
      - "8080:8080"  
    depends_on:
      - db

volumes:
  db_data:
